- name: Check if Directory exists
  shell: "{{JENKINS_CLI_PREFIX}} get-job {{item.name}}"
  ignore_errors: true
  register: check_dir




- name: update job template
  template:
    src: folders-job.xml
    dest: /tmp/job.xml

- name: Create a Directory
  when: check_dir.rc == 3
  shell: "cat /tmp/job.xml | {{JENKINS_CLI_PREFIX}} create-job {{item.name}}"

- name: Update directory
  when: check_dir.rc == 0
  shell: "cat /tmp/job.xml | {{JENKINS_CLI_PREFIX}} update-job {{item.name}}"
