- name: Check the Jenkins connection
  shell: "{{JENKINS_CLI_PREFIX}} who-am-i"

- name: Create jenkins Multi branch job
  include_tasks: mb-job.yml
  loop:
    - {name: "cart", repoName: "cart"}


- name: Create jenkins Folder job
  include_tasks: folders-job.yml
  loop:
    - {name: "CI-Pipelines", description: "ALL-CI-Pipelines" }


